name: flutter_herexamen_noah2023
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  http: ^0.13.5
  audioplayers: ^2.0.0
  flutter_email_sender: ^5.2.0
  email_validator: ^2.1.17
  url_launcher: ^6.1.10
  video_player: ^2.6.0
  mongo_dart: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/flutter.png
    - assets/images/programminglanguages.png
    - assets/images/widgettree.png
    - assets/images/placeholder.png
    - assets/audio/goed.mp3
    - assets/audio/fout.mp3
    - assets/video/introICT.mp4
    - assets/video/introhistory.mp4
